version: "3"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: backend-image
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL = mongodb+srv://admin:123pass123@cluster0.lriapqd.mongodb.net/?retryWrites=true&w=majority
    networks:
      - data-analysis-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: frontend-image
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - data-analysis-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_URL = mongodb+srv://admin:123pass123@cluster0.lriapqd.mongodb.net/?retryWrites=true&w=majority
    networks:
      - data-analysis-network

networks:
  data-analysis-network:
    driver: bridge
